CREATE TABLE "heroes" (
  "id" bigint NULL,
  "localized_name" text NULL,
  "primary_attr" text NULL,
  "attack_type" text NULL,
  "roles" json NULL
);

INSERT INTO "heroes" ("id","localized_name","primary_attr","attack_type","roles")
VALUES
(102,'Abaddon','all','Melee','["Support","Carry","Durable"]'),
(73,'Alchemist','str','Melee','["Carry","Support","Durable","Disabler","Initiator","Nuker"]'),
(68,'Ancient Apparition','int','Ranged','["Support","Disabler","Nuker"]'),
(1,'Anti-Mage','agi','Melee','["Carry","Escape","Nuker"]'),
(113,'Arc Warden','agi','Ranged','["Carry","Escape","Nuker"]'),
(2,'Axe','str','Melee','["Initiator","Durable","Disabler","Carry"]'),
(3,'Bane','all','Ranged','["Support","Disabler","Nuker","Durable"]'),
(65,'Batrider','all','Ranged','["Initiator","Disabler","Escape"]'),
(38,'Beastmaster','all','Melee','["Initiator","Disabler","Durable","Nuker"]'),
(4,'Bloodseeker','agi','Melee','["Carry","Disabler","Nuker","Initiator"]'),
(62,'Bounty Hunter','agi','Melee','["Escape","Nuker"]'),
(78,'Brewmaster','all','Melee','["Carry","Initiator","Durable","Disabler","Nuker"]'),
(99,'Bristleback','str','Melee','["Carry","Durable","Initiator","Nuker"]'),
(61,'Broodmother','all','Melee','["Carry","Pusher","Escape","Nuker"]'),
(96,'Centaur Warrunner','str','Melee','["Durable","Initiator","Disabler","Nuker","Escape"]'),
(81,'Chaos Knight','str','Melee','["Carry","Disabler","Durable","Pusher","Initiator"]'),
(66,'Chen','all','Ranged','["Support","Pusher"]'),
(56,'Clinkz','agi','Ranged','["Carry","Escape","Pusher"]'),
(51,'Clockwerk','all','Melee','["Initiator","Disabler","Durable","Nuker"]'),
(5,'Crystal Maiden','int','Ranged','["Support","Disabler","Nuker"]'),
(55,'Dark Seer','all','Melee','["Initiator","Escape","Disabler"]'),
(119,'Dark Willow','all','Ranged','["Support","Nuker","Disabler","Escape"]'),
(135,'Dawnbreaker','str','Melee','["Carry","Durable"]'),
(50,'Dazzle','all','Ranged','["Support","Nuker","Disabler"]'),
(43,'Death Prophet','int','Ranged','["Carry","Pusher","Nuker","Disabler"]'),
(87,'Disruptor','int','Ranged','["Support","Disabler","Nuker","Initiator"]'),
(69,'Doom','str','Melee','["Carry","Disabler","Initiator","Durable","Nuker"]'),
(49,'Dragon Knight','str','Melee','["Carry","Pusher","Durable","Disabler","Initiator","Nuker"]'),
(6,'Drow Ranger','agi','Ranged','["Carry","Disabler","Pusher"]'),
(107,'Earth Spirit','str','Melee','["Nuker","Escape","Disabler","Initiator","Durable"]'),
(7,'Earthshaker','str','Melee','["Support","Initiator","Disabler","Nuker"]'),
(103,'Elder Titan','str','Melee','["Initiator","Disabler","Nuker","Durable"]'),
(106,'Ember Spirit','agi','Melee','["Carry","Escape","Nuker","Disabler","Initiator"]'),
(58,'Enchantress','int','Ranged','["Support","Pusher","Durable","Disabler"]'),
(33,'Enigma','all','Ranged','["Disabler","Initiator","Pusher"]'),
(41,'Faceless Void','agi','Melee','["Carry","Initiator","Disabler","Escape","Durable"]'),
(121,'Grimstroke','int','Ranged','["Support","Nuker","Disabler","Escape"]'),
(72,'Gyrocopter','agi','Ranged','["Carry","Nuker","Disabler"]'),
(123,'Hoodwink','agi','Ranged','["Support","Nuker","Escape","Disabler"]'),
(59,'Huskar','str','Ranged','["Carry","Durable","Initiator"]'),
(74,'Invoker','all','Ranged','["Carry","Nuker","Disabler","Escape","Pusher"]'),
(91,'Io','all','Ranged','["Support","Escape","Nuker"]'),
(64,'Jakiro','int','Ranged','["Support","Nuker","Pusher","Disabler"]'),
(8,'Juggernaut','agi','Melee','["Carry","Pusher","Escape"]'),
(90,'Keeper of the Light','int','Ranged','["Support","Nuker","Disabler"]'),
(145,'Kez','agi','Melee','["Carry","Escape","Disabler"]'),
(23,'Kunkka','str','Melee','["Carry","Support","Disabler","Initiator","Durable","Nuker"]'),
(104,'Legion Commander','str','Melee','["Carry","Disabler","Initiator","Durable","Nuker"]'),
(52,'Leshrac','int','Ranged','["Carry","Support","Nuker","Pusher","Disabler"]'),
(31,'Lich','int','Ranged','["Support","Nuker"]'),
(54,'Lifestealer','str','Melee','["Carry","Durable","Escape","Disabler"]'),
(25,'Lina','int','Ranged','["Support","Carry","Nuker","Disabler"]'),
(26,'Lion','int','Ranged','["Support","Disabler","Nuker","Initiator"]'),
(80,'Lone Druid','all','Ranged','["Carry","Pusher","Durable"]'),
(48,'Luna','agi','Ranged','["Carry","Nuker","Pusher"]'),
(77,'Lycan','all','Melee','["Carry","Pusher","Durable","Escape"]'),
(97,'Magnus','all','Melee','["Initiator","Disabler","Nuker","Escape"]'),
(136,'Marci','all','Melee','["Support","Carry","Initiator","Disabler","Escape"]'),
(129,'Mars','str','Melee','["Carry","Initiator","Disabler","Durable"]'),
(94,'Medusa','agi','Ranged','["Carry","Disabler","Durable"]'),
(82,'Meepo','agi','Melee','["Carry","Escape","Nuker","Disabler","Initiator","Pusher"]'),
(9,'Mirana','all','Ranged','["Carry","Support","Escape","Nuker","Disabler"]'),
(114,'Monkey King','agi','Melee','["Carry","Escape","Disabler","Initiator"]'),
(10,'Morphling','agi','Ranged','["Carry","Escape","Durable","Nuker","Disabler"]'),
(138,'Muerta','int','Ranged','["Carry","Nuker","Disabler"]'),
(89,'Naga Siren','agi','Melee','["Carry","Support","Pusher","Disabler","Initiator","Escape"]'),
(53,'Nature''s Prophet','int','Ranged','["Carry","Pusher","Escape","Nuker"]'),
(36,'Necrophos','int','Ranged','["Carry","Nuker","Durable","Disabler"]'),
(60,'Night Stalker','str','Melee','["Carry","Initiator","Durable","Disabler","Nuker"]'),
(88,'Nyx Assassin','all','Melee','["Disabler","Nuker","Initiator","Escape"]'),
(84,'Ogre Magi','str','Melee','["Support","Nuker","Disabler","Durable","Initiator"]'),
(57,'Omniknight','str','Melee','["Support","Durable","Nuker"]'),
(111,'Oracle','int','Ranged','["Support","Nuker","Disabler","Escape"]'),
(76,'Outworld Destroyer','int','Ranged','["Carry","Nuker","Disabler"]'),
(120,'Pangolier','all','Melee','["Carry","Nuker","Disabler","Durable","Escape","Initiator"]'),
(44,'Phantom Assassin','agi','Melee','["Carry","Escape"]'),
(12,'Phantom Lancer','agi','Melee','["Carry","Escape","Pusher","Nuker"]'),
(110,'Phoenix','all','Ranged','["Support","Nuker","Initiator","Escape","Disabler"]'),
(137,'Primal Beast','str','Melee','["Initiator","Durable","Disabler"]'),
(13,'Puck','int','Ranged','["Initiator","Disabler","Escape","Nuker"]'),
(14,'Pudge','str','Melee','["Disabler","Initiator","Durable","Nuker"]'),
(45,'Pugna','int','Ranged','["Nuker","Pusher"]'),
(39,'Queen of Pain','int','Ranged','["Carry","Nuker","Escape"]'),
(15,'Razor','agi','Ranged','["Carry","Durable","Nuker","Pusher"]'),
(32,'Riki','agi','Melee','["Carry","Escape","Disabler"]'),
(131,'Ringmaster','int','Ranged','["Support","Nuker","Escape","Disabler"]'),
(86,'Rubick','int','Ranged','["Support","Disabler","Nuker"]'),
(16,'Sand King','all','Melee','["Initiator","Disabler","Support","Nuker","Escape"]'),
(79,'Shadow Demon','int','Ranged','["Support","Disabler","Initiator","Nuker"]'),
(11,'Shadow Fiend','agi','Ranged','["Carry","Nuker"]'),
(27,'Shadow Shaman','int','Ranged','["Support","Pusher","Disabler","Nuker","Initiator"]'),
(75,'Silencer','int','Ranged','["Carry","Support","Disabler","Initiator","Nuker"]'),
(101,'Skywrath Mage','int','Ranged','["Support","Nuker","Disabler"]'),
(28,'Slardar','str','Melee','["Carry","Durable","Initiator","Disabler","Escape"]'),
(93,'Slark','agi','Melee','["Carry","Escape","Disabler","Nuker"]'),
(128,'Snapfire','all','Ranged','["Support","Nuker","Disabler","Escape"]'),
(35,'Sniper','agi','Ranged','["Carry","Nuker"]'),
(67,'Spectre','agi','Melee','["Carry","Durable","Escape"]'),
(71,'Spirit Breaker','str','Melee','["Carry","Initiator","Disabler","Durable","Escape"]'),
(17,'Storm Spirit','int','Ranged','["Carry","Escape","Nuker","Initiator","Disabler"]'),
(18,'Sven','str','Melee','["Carry","Disabler","Initiator","Durable","Nuker"]'),
(105,'Techies','all','Ranged','["Nuker","Disabler"]'),
(46,'Templar Assassin','agi','Ranged','["Carry","Escape"]'),
(109,'Terrorblade','agi','Melee','["Carry","Pusher","Nuker"]'),
(29,'Tidehunter','str','Melee','["Initiator","Durable","Disabler","Nuker","Carry"]'),
(98,'Timbersaw','str','Melee','["Nuker","Durable","Escape"]'),
(34,'Tinker','int','Ranged','["Carry","Nuker","Pusher"]'),
(19,'Tiny','str','Melee','["Carry","Nuker","Pusher","Initiator","Durable","Disabler"]'),
(83,'Treant Protector','str','Melee','["Support","Initiator","Durable","Disabler","Escape"]'),
(95,'Troll Warlord','agi','Ranged','["Carry","Pusher","Disabler","Durable"]'),
(100,'Tusk','str','Melee','["Initiator","Disabler","Nuker"]'),
(108,'Underlord','str','Melee','["Support","Nuker","Disabler","Durable","Escape"]'),
(85,'Undying','str','Melee','["Support","Durable","Disabler","Nuker"]'),
(70,'Ursa','agi','Melee','["Carry","Durable","Disabler"]'),
(20,'Vengeful Spirit','all','Ranged','["Support","Initiator","Disabler","Nuker","Escape"]'),
(40,'Venomancer','all','Ranged','["Support","Nuker","Initiator","Pusher","Disabler"]'),
(47,'Viper','agi','Ranged','["Carry","Durable","Initiator","Disabler"]'),
(92,'Visage','all','Ranged','["Support","Nuker","Durable","Disabler","Pusher"]'),
(126,'Void Spirit','all','Melee','["Carry","Escape","Nuker","Disabler"]'),
(37,'Warlock','int','Ranged','["Support","Initiator","Disabler"]'),
(63,'Weaver','agi','Ranged','["Carry","Escape"]'),
(21,'Windranger','all','Ranged','["Carry","Support","Disabler","Escape","Nuker"]'),
(112,'Winter Wyvern','all','Ranged','["Support","Disabler","Nuker"]'),
(30,'Witch Doctor','int','Ranged','["Support","Nuker","Disabler"]'),
(42,'Wraith King','str','Melee','["Carry","Support","Durable","Disabler","Initiator"]'),
(22,'Zeus','int','Ranged','["Nuker","Carry"]');

SELECT * FROM heroes;